### PR TITLE
Use ESM instead of CJS. Potentially fixes #160

### LINKED ISSUE #160: ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING error when using ESM script to render
When trying to use a ESM script with the library I'm getting a ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING error on the line that dynamically imports the script.
```
A dynamic import callback was not specified. TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified. at new NodeError (node:internal/errors:399:5) at importModuleDynamicallyCallback (node:internal/modules/esm/utils:89:9) at Http2ServerRequest. ([eval]:1:3021) at Http2ServerRequest.emit (node:events:512:28) at endReadableNT (node:internal/streams/readable:1359:12) at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
at Jering.Javascript.NodeJS.HttpNodeJSService.TryInvokeAsync[T](InvocationRequest invocationRequest, CancellationToken cancellationToken)
at Jering.Javascript.NodeJS.OutOfProcessNodeJSService.TryInvokeCoreAsync[T](InvocationRequest invocationRequest, CancellationToken cancellationToken)
at Jering.Javascript.NodeJS.OutOfProcessNodeJSService.InvokeFromFileAsync[T](String modulePath, String exportName, Object[] args, CancellationToken cancellationToken)
```

This is the line from the Javascript.NodeJS library minified script that causes the exception:
```
      a = e.endsWith(".mjs") ? await import("file:///" + e.replaceAll("\\", "/")) : require(e)
```

The script with "mjs" extension looks very simple:
```
export default async(data) => {
  console.log("render called");
  return Promise.resolve("Test");
};
```

The strange thing is also that initially it does seem to work, so some calls are successful, but then it stops working with that error.

Any ideas?

I'm using node 19.7.0 and 7.0.0-beta3 of this library.

### PR DESCRIPTION
**Pull request by aKzenT**
This moves the JS contained in the project from CJS to ESM, which improves interoperability and potentially fixes #160

### CODE REVIEW

File: src/NodeJS/NodeJSServiceImplementations/OutOfProcess/NodeJSProcessFactory.cs [hunk 1]
```diff
@@ -48,7 +48,7 @@ internal ProcessStartInfo CreateStartInfo(string nodeServerScript)
 #endif
             var startInfo = new ProcessStartInfo(_nodeJSProcessOptions.ExecutablePath!) // ConfigureNodeJSProcessOptions sets ExecutablePath to "node" if user specified value is null, whitespace or an empty string
             {
-                Arguments = $"{_nodeJSProcessOptions.NodeAndV8Options} -e \"{nodeServerScript}\" -- --parentPid {currentProcessPid} --port {_nodeJSProcessOptions.Port}",
+                Arguments = $"{_nodeJSProcessOptions.NodeAndV8Options} --input-type=module -e \"{nodeServerScript}\" -- --parentPid {currentProcessPid} --port {_nodeJSProcessOptions.Port}",
```
Comment (thebuilder) [inline src/NodeJS/NodeJSServiceImplementations/OutOfProcess/NodeJSProcessFactory.cs:51]: This argument would not be necessary if one of these is true:

- Files are changed to `.mjs`
-`package.json` has `"type": "module" (requires the `package.json` to be in the `cwd()`)

This would be a better solution, so it's clear what the output is.

File: src/NodeJS/Javascript/package.json [hunk 2]
```diff
@@ -1,13 +1,12 @@
 {
     "private": true,
+    "type": "module",
```
Comment (thebuilder) [inline src/NodeJS/Javascript/package.json:3]: Is node correctly running the bundled files? Just wondering if it correctly detects the `package.json`, so it can see the `type: "module"`. Otherwise it would see the compiled `.js` files as CommonJS.

File: src/NodeJS/Jering.Javascript.NodeJS.csproj [hunk 3]
```diff
@@ -97,8 +97,8 @@
         If we aren't multi-targeting, JavascriptBuild runs before PreBuildEvent.
     -->
     <Target Name="JavascriptBuildWindows" BeforeTargets="DispatchToInnerBuilds" Inputs="@(JavascriptInputs)" Outputs="@(JavascriptOutputs)">
-        <Yarn WorkingDirectory=".\Javascript" Command="run build --env mode=$(Configuration) --env entry=./Servers/OutOfProcess/Http/Http11Server.ts" />
-        <Yarn WorkingDirectory=".\Javascript" Command="run build --env mode=$(Configuration) --env entry=./Servers/OutOfProcess/Http/Http20Server.ts" />
+        <Yarn WorkingDirectory=".\Javascript" Command="run build --ssr ./Servers/OutOfProcess/Http/Http11Server.ts --outDir bin/$(Configuration)" />
```
Comment (thebuilder) [inline src/NodeJS/Jering.Javascript.NodeJS.csproj:100]: Could we add a `<Yarn WorkingDirectory=".\Javascript" />` task here, to trigger the `yarn install`.

File: src/NodeJS/Javascript/package.json (hunk 2 above)
Comment (aKzenT) [reply src/NodeJS/Javascript/package.json:3]: This is only relevant during the build of the library itself. The compiled files are embedded in the library and are passed to nodejs as a string on the command line. For this reason we have to specify `--input-type=module` as well when calling node. We cannot depend on any package.json being present at the time of execution, because there could be none and also the compiled file is always ESM regardless of what the package.json in the CWD specifies.

File: src/NodeJS/Jering.Javascript.NodeJS.csproj (hunk 3 above)
Comment (aKzenT) [reply src/NodeJS/Jering.Javascript.NodeJS.csproj:100]: do you mean to avoid calling yarn install twice? I'm certainly open to that, although I don't think it makes much of a difference as the second yarn install will return very fast. I was trying in the PR to keep the setup as close to the webpack one as possible to make it easier for @JeremyTCD to approve it. Also I'm not an MSBuild expert, so I'm not completely sure what happens if we add another task here, if that would execute sequentially or in parallel.

Comment (thebuilder) [reply src/NodeJS/Jering.Javascript.NodeJS.csproj:100]: Just seems like the correct way of doing it, but not a biggie if the other way works. :)

**Comment by JeremyTCD** [comment]
While using Vite's server-side rendering functionality to produce our bundle for an unintended purpose raises some concerns, everything works as expected and our setup is now simpler and more concise than before. Therefore, this pull request looks good overall.

I have released 7.0.0-beta.5 with the changes in this pr.

@thebuilder, I have added you to the contributors section of the ReadMe.md file since some of the code in this pull request was originally from your pull request.

@aKzenT, I have assigned you write privileges for the repository so that you can merge changes without having to wait for me in the future.

**Comment by thebuilder** [comment]
Awesome Jeremy.

We can look into using another build tool for bundling the scripts - There's a bunch of them. But as a direct replacement for Webpack, Vite is the closest.
